# Generated by Django 5.2.8 on 2025-11-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_path',
            field=models.CharField(blank=True, help_text='Caminho do avatar no storage para deleção', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL do avatar no Supabase Storage', null=True),
        ),
    ]
