# Generated by Django 5.2.8 on 2025-11-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_2_path_product_image_2_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='campus',
            field=models.CharField(choices=[('gama', 'Campus Gama'), ('darcy-ribeiro', 'Campus Darcy Ribeiro'), ('planaltina', 'Campus Planaltina'), ('ceilandia', 'Campus Ceilândia'), ('fcte', 'Campus FCTE')], max_length=20),
        ),
    ]
